- name: Create a tmp work directory
  file:
    path: /tmp/omnisci/tpc-ds
    state: directory
    mode: '0755'
- name: Upload TPC-DS DDL for Omnisci
  template: src=1_omnisci-tpcds-ddl.sql dest=/tmp/omnisci/tpc-ds/
- name: Upload TPC-DS DDL with partitions for Omnisci
  template: src=1_omnisci-tpcds-ddl_partitions.sql dest=/tmp/omnisci/tpc-ds/
- name: Upload TPC-DS User Definition for Omnisci
  template: src=2_omnisci-tpcds-user.sql dest=/tmp/omnisci/tpc-ds/
- name: Upload TPC-DS LOCAL Load Script for Omnisci
  template: src=3_omnisci-load-local-data.sql dest=/tmp/omnisci/tpc-ds/
  when: dataimport_type == 'localfs'
- name: Upload TPC-DS AWS S3 Load Script for Omnisci
  template: src=3_omnisci-load-s3-data.sql dest=/tmp/omnisci/tpc-ds/
  when: dataimport_type == 's3'


- name: Create TPC-DS Schema and Tables in Omnisci
  shell: "/opt/gpudb/bin/kisql --host localhost --user {{ omnisci_admin_user }} --file /tmp/omnisci/tpc-ds/1_omnisci-tpcds-ddl.sql"
  environment:
    KI_PWD: "{{ omnisci_admin_password }}"
  when: omnisci_tpcds_with_partitions == 'no'
- name: Create TPC-DS Schema and Tables with partitions in Omnisci
  shell: "/opt/gpudb/bin/kisql --host localhost --user {{ omnisci_admin_user }} --file /tmp/omnisci/tpc-ds/1_omnisci-tpcds-ddl_partitions.sql"
  environment:
    KI_PWD: "{{ omnisci_admin_password }}"
  when: omnisci_tpcds_with_partitions == 'yes'
- name: Create TPC-DS Test User and Permissions
  shell: "/opt/gpudb/bin/kisql --host localhost --user {{ omnisci_admin_user }} --file /tmp/omnisci/tpc-ds/2_omnisci-tpcds-user.sql"
  environment:
    KI_PWD: "{{ omnisci_admin_password }}"
- name: Load LOCAL TPC-DS Data into Omnisci
  shell: "/opt/gpudb/bin/kisql --host localhost --user {{ omnisci_admin_user }} --file /tmp/omnisci/tpc-ds/3_omnisci-load-local-data.sql"
  environment:
    KI_PWD: "{{ omnisci_admin_password }}"
  when: dataimport_type == 'localfs'
- name: Load AWS S3 TPC-DS Data into Omnisci
  shell: "/opt/gpudb/bin/kisql --host localhost --user {{ omnisci_admin_user }} --file /tmp/omnisci/tpc-ds/3_omnisci-load-s3-data.sql"
  environment:
    KI_PWD: "{{ omnisci_admin_password }}"
  when: dataimport_type == 's3'
