- name: Set JMeter Test Params
  hosts: all
  tasks:
    - set_fact:
        jmeter_test_name: kinetica-tpch
        # jmeter_path: "{{ jmeter_path_result.files[0].path }}"
        date_info: "{{ ansible_date_time.date }}.{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}"
    - set_fact:
        result_path: "/opt/benchmarks/results/{{ jmeter_test_name }}-{{ date_info }}/"
- name: JMeter - Run Kinetica TPC-H Benchmark
  hosts: jmeter
  roles:
    - {role: jmeter-run-kinetica-tpch }
- name: Fetch Kinetica Config and put in results dir
  hosts: kinetica[0]
  tasks:
    - name: Fetch results to local
      fetch:
        src: "/opt/gpudb/core/etc/gpudb.conf"
        dest: "{{ jmeter_local_result_path }}/{{ jmeter_test_name }}-{{ date_info }}/"
        flat: yes